---
title: "Uvod"
output: html_document
---

 


Tečaj *Upoznavanje sa sintaksom jezika R i njegova primjena u osnovnoj statističkoj i grafičkoj analizi podataka (S720)* obrađuje osnove rada u okruženju programskog jezika R te njegovo korištenje u pripremi, vizualizaciji i statističkoj analizi podataka. Ovaj tečaj osmišljen je s ciljem upoznavanja sudionika s mogućnostima sustava, dajući generalni pregled tema i područja važnih za osobe koje se bave znanostima o podacima. Tečaj je namijenjen najširoj publici i raznolikim strukama. Pojedine će teme sudionicima biti od većeg ili manjeg značaja za njihovo specifično područje, a proizašle su iz višegodišnjeg iskustva autorice tečaja kao nužne. Polaznicima je pokušano dati što bolji temelj i informacije o dijelovim sustava o kojima je barem bitno znati da postoje kako bi se njihove te funkcionalnosti potražile i koristile prema potrebi. Savladavanjem gradiva tečaja polaznici će u potpunosti biti u mogućnosti pratiti nadogradnje putem drugih tečajeva Srca vazanih uz sustav R i manipulacije podacima te reproducibilno istraživanje.

Tečaj je namijenjen polaznicima koji se po prvi puta susreću kako s okruženjem programskog jezika R tako i s analizama podataka.

Za pohađanje ovog tečaja potrebno je poznavanje osnova rada s računalom i operacijskim sustavom MS Windows (iako većina napisanog vrijedi i za npr. Ubuntu sustav) te poznavanje osnova rada na Internetu. Također, pasivno poznavanje engleskog jezika nužno je u radu sa sustavom R.

Preporučamo samostalno upoznavanje s materijelima on-line tečaja Srca "Zašto učiti R?" na lms.srce.hr.

Minimalno iskustvo programiranja je prednost.

